use ar;
-- Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) from ar.customer_shopping
group by 1;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select purchase_amount,discount_applied,customer_id from ar.customer_shopping
where discount_applied="Yes" and purchase_amount >
 (select avg(purchase_amount) from ar.customer_shopping);
 
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) from ar.customer_shopping
group by 1 order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,avg(purchase_amount) from ar.customer_shopping
where shipping_type="Standard" or shipping_type="Express" 
group by 1;

--  Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,round(avg(purchase_amount),2),sum(purchase_amount) ,count(customer_id) 
from ar.customer_shopping
group by 1;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(sum(case when discount_applied ="Yes"  Then 1 else 0 end)/count(*) *100,2) as discount_rate
from ar.customer_shopping
group by item_purchased
order by discount_rate desc
limit 5;
 
-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with csr as
(select customer_id,previous_purchases,
case
	when previous_purchases = 1 then "new"
    when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
    from ar.customer_shopping
)
select customer_segment, count(customer_segment) from csr
group by 1;
-- Q8. What are the top 3 most purchased products within each category? 
with ric as
(select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as rank_item
from ar.customer_shopping
group by category,item_purchased)

select rank_item,category,item_purchased from ric
where rank_item <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) from ar.customer_shopping
where previous_purchases >=5
group by 1;
-- Q10. What is the revenue contribution of each age group? 
 select age_group,sum(purchase_amount) as total_revenue from ar.customer_shopping
 group by 1 order by total_revenue desc;

-- contribution of each age group in total revenue in percentage 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 /
        (SELECT SUM(purchase_amount)
         FROM ar.customer_shopping),
        2
    ) AS revenue_contribution_percent
FROM ar.customer_shopping
GROUP BY age_group
ORDER BY revenue_contribution_percent DESC;